version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '2345:2345'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./coleyfrontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./coleyfrontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./coleyapp
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=Ric1991!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=coleydb

    ports:
      - '8000:8000'

    volumes:
      - ./coleyapp:/app/backend

    depends_on:
      - db
