# Generated by Django 4.1.6 on 2023-02-16 00:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('groups', models.IntegerField()),
                ('user_permissions', models.IntegerField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('result_xlsx_path', models.FileField(upload_to='uploads/')),
                ('state', models.TextField()),
            ],
            options={
                'db_table': 'analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('container_id', models.IntegerField(primary_key=True, serialize=False)),
                ('container_name', models.CharField(max_length=255)),
                ('container_description', models.TextField()),
            ],
            options={
                'db_table': 'containers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('cut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cut_number', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('cut_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('entry_date', models.DateTimeField()),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temperature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TumorType',
            fields=[
                ('tumor_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('tumor_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tumor_type',
                'managed': False,
            },
        ),
    ]
