# Generated by Django 4.1.6 on 2023-03-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coleyapi', '0002_tissuetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tissuetype',
            options={'managed': True},
        ),
    ]
